services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '3000:8080'
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-U'
        - postgres
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: null
