name: Build e Teste do Projeto

on:
  # O workflow será executado quando houver um push para o branch principal
  push:
    branches: ["main"]
  # Ou quando um pull request for aberto contra o branch principal
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install
