name: Build e Teste do Projeto

on:
  # O workflow será executado quando houver um push para o branch principal
  push:
    branches: ["main"]
  # Ou quando um pull request for aberto contra o branch principal
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Compile o projeto (sem testes)
        run: mvn -B clean compile

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: minhascontas
          POSTGRES_USER: usuario
          POSTGRES_PASSWORD: senha
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Carregar variáveis do .env no ambiente
        run: |
          if [ -f .env ]; then
            echo "Carregando variáveis do .env..."
            while IFS= read -r line; do
              if [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
                echo "$line" >> $GITHUB_ENV
              fi
            done < .env
          else
            echo "Arquivo .env não encontrado!"
            exit 1
          fi

      - name: Executar os testes
        run: mvn test
